# Generated by Omarchy from ~/.config/omarchy/themed/starship.toml.tpl. Do not edit.
# Edit the .tpl instead, then run: omarchy theme set "$(cat ~/.local/state/omarchy/current/theme.name)"

add_newline = false
palette = "omarchy"

format = """
$sudo$cmd_duration$jobs 󰜥 $directory$git_branch$git_status$git_state$git_metrics$nodejs$python$rust$golang$lua$mise$direnv$nix_shell$conda$docker_context$container
$character"""

# ────────────────────────────
# Prompt Character (Triangle)
# ────────────────────────────
[character]
success_symbol = "[❯](fg:mauve)"
error_symbol = "[❯](fg:red)"
vimcmd_symbol = "[❮](fg:green)"
vimcmd_replace_one_symbol = "[❮](fg:peach)"
vimcmd_replace_symbol = "[❮](fg:peach)"
vimcmd_visual_symbol = "[❮](fg:yellow)"

# ────────────────────────────
# Sudo / Jobs (only show when active)
# ────────────────────────────
[sudo]
disabled = false
symbol = " "
format = "[$symbol]($style)"
style = "fg:yellow"

[jobs]
disabled = false
symbol = "󰜮 "
format = " [$symbol$number]($style)"
style = "fg:peach"
threshold = 1

# ────────────────────────────
[package]
disabled = true

# ────────────────────────────
# Git Branch (minimal, colored text)
# ────────────────────────────
[git_branch]
symbol = "󰘬"
truncation_length = 30
style = "fg:blue"
format = "[ $symbol $branch(:$remote_branch)]($style)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "
only_detached = false
tag_disabled = false

[git_state]
format = '[ \($state( $progress_current of $progress_total)\)]($style)'
style = "fg:yellow"
cherry_pick = "CHERRY-PICKING"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"

[git_metrics]
disabled = false
added_style = "fg:green"
deleted_style = "fg:red"
format = '([ +$added]($added_style))([-$deleted]($deleted_style))'
only_nonzero_diffs = true
ignore_submodules = true

# ────────────────────────────
[git_status]
format = '[$all_status$ahead_behind]($style)'
disabled = false
style = "fg:text"
conflicted = '[ ≠$count](fg:red)'
ahead = '[ ⇡$count](fg:green)'
behind = '[ ⇣$count](fg:red)'
diverged = '[ ⇕⇡$ahead_count⇣$behind_count](fg:yellow)'
untracked = '[ ?$count](fg:yellow)'
stashed = '[ ≡$count](fg:cyan)'
modified = '[ !$count](fg:yellow)'
staged = '[ +$count](fg:green)'
renamed = '[ »$count](fg:blue)'
deleted = '[ ✘$count](fg:red)'
typechanged = '[ ⟲$count](fg:magenta)'
up_to_date = ""

# ────────────────────────────
[username]
show_always = false
format = "[$user]($style)@"
style_user = "fg:accent"
style_root = "fg:red"
disabled = false

[hostname]
ssh_only = false
ssh_symbol = "🌐 "
format = "•$hostname"
trim_at = ".companyname.com"
disabled = false

# ────────────────────────────
# Directory (minimal green accent)
# ────────────────────────────
[directory]
home_symbol = "  "
read_only = "  "
read_only_style = "fg:red"
style = "fg:green"
truncation_length = 6
truncation_symbol = "••/"
format = '[󰉋 $path]($style)[$read_only]($read_only_style)'
truncate_to_repo = true

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "
"Projects" = " 󰏖 "
"Code" = "  "

# ────────────────────────────
# Command Duration
# ────────────────────────────
[cmd_duration]
min_time = 500
show_milliseconds = false
style = "fg:peach"
format = '[󰪢 $duration]($style)'

# ────────────────────────────
# Toolchains (only show when relevant to cwd)
# ────────────────────────────
[nodejs]
format = ' via [$symbol($version )]($style)'
symbol = " "
style = "fg:green"
disabled = false

[python]
format = ' via [$symbol($version )(\($virtualenv\) )]($style)'
symbol = " "
style = "fg:yellow"
disabled = false

[rust]
format = ' via [$symbol($version )]($style)'
symbol = " "
style = "fg:red"
disabled = false

[golang]
format = ' via [$symbol($version )]($style)'
symbol = " "
style = "fg:cyan"
disabled = false

[lua]
format = ' via [$symbol($version )]($style)'
symbol = " "
style = "fg:blue"
disabled = false

[mise]
format = ' via [$symbol($version )]($style)'
symbol = "⏺ "
style = "fg:accent"
disabled = false

[direnv]
format = ' [$symbol$loaded/$allowed]($style)'
symbol = "direnv "
style = "fg:muted"
disabled = false
denied_msg = "denied"
loaded_msg = "loaded"
unloaded_msg = "not loaded"

[nix_shell]
format = ' via [$symbol$state( \($name\))]($style) '
symbol = " "
style = "fg:cyan"
disabled = false

[conda]
format = ' via [$symbol$environment]($style) '
symbol = "🅒 "
style = "fg:green"
disabled = false
ignore_base = true

[docker_context]
format = ' via [$symbol$context]($style) '
symbol = " "
style = "fg:blue"
disabled = false
only_with_files = true

[container]
format = ' [$symbol \[$name\]]($style)'
symbol = "⬢"
style = "fg:red"
disabled = false

# ────────────────────────────
# System (quiet by default)
# ────────────────────────────
[os]
disabled = true
format = "[$symbol]($style)"
style = "fg:muted"

[os.symbols]
Arch = "󰣇 "
Linux = "󰌽 "

[memory_usage]
disabled = true
format = "via $symbol[${ram}( | ${swap})]($style) "
symbol = "🐏 "
style = "fg:muted"
threshold = 75

[battery]
disabled = false
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 15
style = "red bold"

[time]
disabled = true
format = "[$time]($style) "
style = "fg:muted"
time_format = "%R"

[status]
disabled = true
format = "[$symbol$status]($style) "
symbol = "✗ "
style = "fg:red"

# ────────────────────────────
# Omarchy theme palette (rendered on every `omarchy theme set`)
# ────────────────────────────
[palettes.omarchy]
accent = "{{ accent }}"
background = "{{ background }}"
foreground = "{{ foreground }}"
bright_foreground = "{{ bright_foreground }}"
light_foreground = "{{ light_foreground }}"
dark_foreground = "{{ dark_foreground }}"
selection = "{{ selection }}"
muted = "{{ muted }}"
red = "{{ red }}"
bright_red = "{{ bright_red }}"
green = "{{ green }}"
bright_green = "{{ bright_green }}"
yellow = "{{ yellow }}"
bright_yellow = "{{ bright_yellow }}"
blue = "{{ blue }}"
bright_blue = "{{ bright_blue }}"
magenta = "{{ magenta }}"
bright_magenta = "{{ bright_magenta }}"
cyan = "{{ cyan }}"
bright_cyan = "{{ bright_cyan }}"
orange = "{{ orange }}"
brown = "{{ brown }}"
# Compat aliases for the previous catppuccin_mocha names used above
mauve = "{{ magenta }}"
peach = "{{ orange }}"
pink = "{{ magenta }}"
teal = "{{ cyan }}"
sky = "{{ cyan }}"
sapphire = "{{ blue }}"
lavender = "{{ blue }}"
text = "{{ foreground }}"
subtext1 = "{{ light_foreground }}"
subtext0 = "{{ dark_foreground }}"
overlay2 = "{{ muted }}"
overlay1 = "{{ muted }}"
overlay0 = "{{ dark_foreground }}"
surface2 = "{{ selection }}"
surface1 = "{{ selection }}"
surface0 = "{{ selection }}"
base = "{{ background }}"
mantle = "{{ dark_background }}"
crust = "{{ darker_background }}"
rosewater = "{{ foreground }}"
flamingo = "{{ light_foreground }}"
maroon = "{{ orange }}"
