# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Application workspace rules
windowrule = match:class ^(ghostty)$, workspace 1
windowrule = match:class ^(zen)$, workspace 2
windowrule = match:class ^(spotify)$, workspace 3
windowrule = match:class ^(todoist)$, workspace 4
