# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Application workspace rules
windowrule = match:class ^(com\.mitchellh\.ghostty)$, workspace 1
windowrule = match:class ^(com\.mitchellh\.ghostty)$, no_blur on
windowrule = match:class ^(com\.mitchellh\.ghostty)$, opacity 1 override 1
windowrule = match:class ^(zen)$, workspace 2
windowrule = match:class ^(zen)$, no_blur on
windowrule = match:class ^(zen)$, opacity 1 override 1
windowrule = match:class ^(spotify)$, workspace 3
windowrule = match:class ^(todoist)$, workspace 4
